#ifndef BLOG_UART_PORT_H
#define BLOG_UART_PORT_H

#define BLOG_UARTx         USART1
#define BLOG_UART_RCC_BIT  RCC_APB2ENR_USART1EN
#define BLOG_UART_RCC_BUS  APB2ENR
#define BLOG_UART_GPIO     GPIOA
#define BLOG_UART_GPIO_RCC RCC_APB2ENR_IOPAEN
#define BLOG_UART_TX_PIN   9u
#define BLOG_UART_RX_PIN   10u
#define BLOG_UART_CLOCK_HZ 72000000u

#endif
