#ifndef SEGGER_RTT_CONF_H
#define SEGGER_RTT_CONF_H

#define SEGGER_RTT_MAX_NUM_UP_BUFFERS   1
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS 1

#define BUFFER_SIZE_UP   256
#define BUFFER_SIZE_DOWN 16

#define SEGGER_RTT_MODE_DEFAULT 0

#define SEGGER_RTT_LOCK()
#define SEGGER_RTT_UNLOCK()

#define SEGGER_RTT_IN_RAM
#define RTT_USE_ASM 0

#define SEGGER_RTT_CPU_CACHE_LINE_SIZE 0

#endif
